server {
    listen 3002;
    server_name _;
    root /usr/share/nginx/html;

    location /ui {
        try_files $uri $uri/ /ui/index.html;
    }

    location = / {
        return 301 /ui;
    }

    location ~ /\. {
        deny all;
    }
}
