services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5757:5757"
    restart: unless-stopped
    depends_on:
      - arangodb
    environment:
      - ARANGO_URL=http://arangodb:8529

  arangodb:
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"
